Repository libgeos/geos, pull requests merged in 2022-11, with the labels that each got.

#724 Improve ConvexHull radial sort robustness
  src/algorithm/ConvexHull.cpp
  tests/unit/algorithm/ConvexHullTest.cpp
Labels: Bug

#728 More robust Delaunay Triangulation frame size heuristic
  include/geos/triangulate/quadedge/QuadEdgeSubdivision.h
  src/triangulate/quadedge/QuadEdgeSubdivision.cpp
  tests/unit/triangulate/DelaunayTest.cpp
  tests/unit/triangulate/VoronoiTest.cpp
  tests/unit/triangulate/quadedge/QuadEdgeSubdivisionTest.cpp
Labels: Bug

#708 Add GEOSLineSubstring
  NEWS.md
  capi/geos_c.cpp
  capi/geos_c.h.in
  capi/geos_ts_c.cpp
  tests/unit/capi/GEOSLineSubstringTest.cpp
  tests/unit/capi/capi_test_utils.h
Labels: Enhancement

#731 Pull CoordinateSequence into SegmentString base class
  include/geos/noding/BasicSegmentString.h
  include/geos/noding/NodableSegmentString.h
  include/geos/noding/NodedSegmentString.h
  include/geos/noding/SegmentString.h
  include/geos/operation/overlayng/Edge.h
  src/noding/BasicSegmentString.cpp
  src/noding/NodedSegmentString.cpp
  src/operation/overlayng/Edge.cpp
  tests/unit/operation/overlayng/OverlayGraphTest.cpp
Labels: Performance
