Repository libgeos/geos, pull requests merged in 2023-05, with the labels that each got.

#899 Fix OffsetCurve parameter handling
  capi/geos_ts_c.cpp
  include/geos/operation/buffer/OffsetCurve.h
  tests/unit/capi/GEOSOffsetCurveTest.cpp
Labels: Bug

#911 geosop: add option to output GeoJSON
  util/geosop/GeosOp.cpp
  util/geosop/GeosOp.h
Labels: Enhancement

#903 Change MultiPoint WKT to use parentheses in sub-members
  NEWS.md
  src/io/WKTWriter.cpp
  tests/unit/algorithm/ConvexHullTest.cpp
  tests/unit/algorithm/distance/DiscreteFrechetDistanceTest.cpp
  tests/unit/algorithm/distance/DiscreteHausdorffDistanceTest.cpp
  tests/unit/capi/GEOSConvexHullTest.cpp
  tests/unit/capi/GEOSDelaunayTriangulationTest.cpp
  tests/unit/capi/GEOSGeomFromWKBTest.cpp
  tests/unit/capi/GEOSGeomToWKBTest.cpp
  tests/unit/capi/GEOSGeomToWKTTest.cpp
  tests/unit/capi/GEOSGeom_createCollectionTest.cpp
  tests/unit/capi/GEOSGeom_extractUniquePointsTest.cpp
  tests/unit/capi/GEOSGetGeometryNTest.cpp
  tests/unit/capi/GEOSSnapTest.cpp
  tests/unit/capi/GEOSUnaryUnionPrecTest.cpp
  tests/unit/capi/GEOSUnaryUnionTest.cpp
  tests/unit/capi/GEOSUnionCascadedTest.cpp
  tests/unit/capi/GEOSUnionPrecTest.cpp
  tests/unit/capi/GEOSUnionTest.cpp
  tests/unit/geom/Geometry/cloneTest.cpp
  tests/unit/geom/Geometry/normalizeTest.cpp
  tests/unit/geom/GeometryFactoryTest.cpp
  tests/unit/geom/MultiPointTest.cpp
  tests/unit/geom/prep/PreparedGeometryFactoryTest.cpp
  tests/unit/io/GeoJSONReaderTest.cpp
  tests/unit/io/WKBReaderTest.cpp
  tests/unit/io/WKTWriterTest.cpp
  tests/unit/operation/cluster/DisjointOperationTest.cpp
  tests/unit/operation/cluster/GeometryFlattenerTest.cpp
  tests/unit/operation/distance/DistanceOpTest.cpp
  tests/unit/simplify/DouglasPeuckerSimplifierTest.cpp
  tests/unit/simplify/TopologyPreservingSimplifierTest.cpp
  tests/unit/triangulate/VoronoiTest.cpp
Labels: Breaking

#908 Change WKBWriter default output dimension to 4
  NEWS.md
  capi/geos_c.h.in
  include/geos/io/WKBWriter.h
  tests/unit/capi/GEOSWKBWriterTest.cpp
  util/geosop/GeosOp.cpp
  web/content/specifications/wkb.md
Labels: Breaking
